[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "py_logger"
version = "0.1.0"
description = "Simple logger for my personal projects"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Kauã M", email = "kauamatheussilva06@gmail.com" },
]
keywords = ["logging", "cli", "utils"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = []

[project.urls]
Repository = "https://github.com/Kaua-Matheus/py_logger"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]